param([string]$AgentRoot="D:\AI3D-Agent",[string]$OutputPath="")
$ErrorActionPreference="Stop";if(-not$OutputPath){$OutputPath=Join-Path $AgentRoot "state\toolchain-preflight.json"}
function Resolve-Tool([string]$Name,[string[]]$Paths=@()){$c=Get-Command $Name -ErrorAction SilentlyContinue|Select-Object -First 1;if($c){return $c.Source};foreach($p in $Paths){try{if(Test-Path -LiteralPath $p -PathType Leaf -ErrorAction Stop){return $p}}catch{}};return $null}
function Import-Works([string]$Python,[string]$Module){if(-not$Python){return $false};try{& $Python -c "import $Module" 2>$null;return($LASTEXITCODE-eq 0)}catch{return $false}}
$python=Resolve-Tool "python" @((Join-Path $AgentRoot "toolchain\cadquery-venv\Scripts\python.exe"),"C:\Users\$env:USERNAME\AppData\Local\Programs\Python\Python312\python.exe")
$osc=Resolve-Tool "openscad" @("C:\Program Files\OpenSCAD\openscad.exe","C:\Program Files (x86)\OpenSCAD\openscad.exe")
$git=Resolve-Tool "git";$codex=Resolve-Tool "codex";$mesh=@();foreach($m in @("trimesh","meshio")){if(Import-Works $python $m){$mesh+=$m}}
$slicers=@(@{name="Anycubic Slicer Next";path=(Resolve-Tool "AnycubicSlicerNext" @("C:\Program Files\AnycubicSlicerNext\AnycubicSlicerNext.exe"));cli_verified=$false},@{name="PrusaSlicer console";path=(Resolve-Tool "prusa-slicer-console" @("C:\Program Files\Prusa3D\PrusaSlicer\prusa-slicer-console.exe"));cli_verified=$true},@{name="OrcaSlicer";path=(Resolve-Tool "orca-slicer" @("C:\Program Files\OrcaSlicer\orca-slicer.exe"));cli_verified=$true})
$r=[ordered]@{schema_version=2;generated_at=(Get-Date).ToString("o");status=$(if($git-and$codex){"PASS"}else{"STOPP"});agent_root=$AgentRoot;tools=[ordered]@{git=@{required=$true;available=[bool]$git;path=$git};codex=@{required=$true;available=[bool]$codex;path=$codex};openscad=@{required=$false;available=[bool]$osc;path=$osc};python=@{required=$false;available=[bool]$python;path=$python};cadquery=@{required=$false;available=(Import-Works $python "cadquery");python=$python};mesh_validation=@{required=$false;available=($mesh.Count-gt 0);modules=$mesh;fallback="repo binary-STL validator"};slicers=$slicers};policy="Optionale Tools blockieren nicht bei reproduzierbarem Ersatzweg; GUI ist kein CLI-Nachweis."}
New-Item -ItemType Directory -Force -Path(Split-Path $OutputPath -Parent)|Out-Null;$r|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $OutputPath -Encoding UTF8;Write-Output $OutputPath;if($r.status-ne"PASS"){exit 2}
